trigger: none

pr:
  branches:
    include:
      - main

stages:
  - stage: PlanAndValidateDev
    displayName: "Dev- Terraform Plan and Validate on PR"
    jobs:
      - template: templates/deploy-template.yml
        parameters:
          environment: 'dev'
          tfvarspath: 'environments/dev/dev.tfvars'
          runApply: false # Do not apply changes on PRs

  - stage: PlanAndValidateProd
    displayName: "Prod - Terraform Plan and Validate on PR"
    jobs:
      - template: templates/deploy-template.yml
        parameters:
          environment: 'prod'
          tfvarspath: 'environments/prod/prod.tfvars'
          runApply: false # Do not apply changes on PRs