
trigger:
- main

pool: digwi-pool

steps:
- script: terraform init
  displayName: Terraform init
  workingDirectory: $(System.DefaultWorkingDirectory)/todo-infra

- script: terraform validate
  displayName: Terraform validate
  workingDirectory: $(System.DefaultWorkingDirectory)/todo-infra

- script: terraform plan -out=tfplan
  displayName: Terraform plan
  workingDirectory: $(System.DefaultWorkingDirectory)/todo-infra

- script: terraform apply --auto-approve tfplan
  displayName: Terraform apply
  workingDirectory: $(System.DefaultWorkingDirectory)/todo-infra


